"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, ChevronUp, Sparkles, Brain } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface AIExplanationProps {
  explanation: string;
  genderPredicted: string;
  confidence: number;
}

export function AIExplanation({
  explanation,
  genderPredicted,
  confidence,
}: AIExplanationProps) {
  const [isExpanded, setIsExpanded] = useState(false);

  const formatExplanation = (text: string) => {
    // Split by sections and format
    const sections = text.split(/\d+\.\s\*\*([^*]+)\*\*:?/g);
    const formattedSections = [];

    for (let i = 1; i < sections.length; i += 2) {
      const title = sections[i];
      const content = sections[i + 1]?.trim();

      if (title && content) {
        formattedSections.push({ title, content });
      }
    }

    return formattedSections.length > 0
      ? formattedSections
      : [{ title: "Analysis", content: text }];
  };

  const sections = formatExplanation(explanation);

  return (
    <Card className="glass-card border-purple-500/30 bg-gradient-to-r from-purple-900/20 to-blue-900/20">
      <CardHeader>
        <CardTitle className="flex items-center justify-between text-gray-100">
          <div className="flex items-center space-x-3">
            <div className="relative">
              <Brain className="w-8 h-8 text-purple-400" />
              <Sparkles className="w-4 h-4 text-yellow-400 absolute -top-1 -right-1" />
            </div>
            <div>
              <h3 className="text-xl font-bold">AI Forensic Analysis</h3>
              <p className="text-sm text-gray-400 font-normal">
                Why the model predicted{" "}
                <span className="text-purple-400 font-semibold">
                  {genderPredicted}
                </span>{" "}
                with {confidence}% confidence
              </p>
            </div>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-gray-300 hover:text-white"
          >
            {isExpanded ? (
              <>
                <ChevronUp className="w-4 h-4 mr-1" />
                Hide Analysis
              </>
            ) : (
              <>
                <ChevronDown className="w-4 h-4 mr-1" />
                Show Analysis
              </>
            )}
          </Button>
        </CardTitle>
      </CardHeader>

      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.3 }}
          >
            <CardContent className="space-y-6">
              {sections.map((section, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1, duration: 0.4 }}
                  className="space-y-3"
                >
                  <h4 className="text-lg font-semibold text-purple-300 flex items-center">
                    <span className="w-2 h-2 bg-purple-400 rounded-full mr-3"></span>
                    {section.title}
                  </h4>
                  <div className="pl-5 border-l-2 border-purple-500/30">
                    <p className="text-gray-300 leading-relaxed whitespace-pre-line">
                      {section.content}
                    </p>
                  </div>
                </motion.div>
              ))}

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5, duration: 0.4 }}
                className="mt-6 p-4 bg-gradient-to-r from-purple-900/30 to-blue-900/30 rounded-lg border border-purple-500/20"
              >
                <p className="text-sm text-gray-400 italic">
                  🧬 This forensic analysis was generated by <span className="text-purple-300 font-semibold">Metric Mind AI</span> based on advanced machine learning and forensic anthropology principles.
                </p>
              </motion.div>
            </CardContent>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  );
}
